name: change_env

on:
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true
      
  qa:
    environment: QA
    needs: build
    name: QA Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deployment 
        run: echo Run QA Deployment.
      
  uat:
    environment: UAT
    needs: qa
    name: UAT Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deployment 
        run: echo Run UAT Deployment.
      
  prod:
    environment: PROD
    needs: uat
    name: Prod Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deployment 
        run: echo Run PROD deployment.    
      
